# Generated by Django 4.1.6 on 2023-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguins', '0002_remove_penguin_body_mass_remove_penguin_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penguin',
            name='bill_depth_mm',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='penguin',
            name='bill_length_mm',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
